// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVuSkklKUOyRIS3fYrv1eBBUQ8WJVCPRQ',
    appId: '1:838451916960:web:2ea3d4f378d11fc39519c5',
    messagingSenderId: '838451916960',
    projectId: 'chat-app-4ed93',
    authDomain: 'chat-app-4ed93.firebaseapp.com',
    storageBucket: 'chat-app-4ed93.firebasestorage.app',
    measurementId: 'G-4CMPJTNFED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxCfWCkRxgSjCFEMY8dSuhtBYIuowh_kc',
    appId: '1:838451916960:android:b5d905a11a6f3cbb9519c5',
    messagingSenderId: '838451916960',
    projectId: 'chat-app-4ed93',
    storageBucket: 'chat-app-4ed93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZImId6tcHvuAeZbK4qAU6_5YUMvoO0Y8',
    appId: '1:838451916960:ios:5d2e6f3e9b106e0d9519c5',
    messagingSenderId: '838451916960',
    projectId: 'chat-app-4ed93',
    storageBucket: 'chat-app-4ed93.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZImId6tcHvuAeZbK4qAU6_5YUMvoO0Y8',
    appId: '1:838451916960:ios:5d2e6f3e9b106e0d9519c5',
    messagingSenderId: '838451916960',
    projectId: 'chat-app-4ed93',
    storageBucket: 'chat-app-4ed93.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVuSkklKUOyRIS3fYrv1eBBUQ8WJVCPRQ',
    appId: '1:838451916960:web:a0caa04c41972fd79519c5',
    messagingSenderId: '838451916960',
    projectId: 'chat-app-4ed93',
    authDomain: 'chat-app-4ed93.firebaseapp.com',
    storageBucket: 'chat-app-4ed93.firebasestorage.app',
    measurementId: 'G-0FQVKHH9T4',
  );
}
